### ISSUE TITLE
Incorrect error message while setting worker concurrency in Kubernetes

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1287]
Kubernetes executor based deployments have default concurrency 1.Setting a worker concurrency should throw an error that indicates that the worker concurrency cannot be set for KubernetesExecutors.The error message currently displayed indicates the minimum machine count related error instead of a concurrency reference
```
shrividyahegde@Shrividyas-MacBook-Pro test_dep % ./astro deployment worker-queue update --concurrency 88
Select a Deployment
 #     DEPLOYMENT NAME     RELEASE NAME                 DEPLOYMENT ID                   DAG DEPLOY ENABLED     
 1     test                true-synodic-0298            cljebq2bf2921391uwqyxrdyx8n     true                   
 2     test health         empty-scintillation-8984     cljeitgb8100681uwwbnwpi5tp      false                  
 3     test111             planetary-gyroscope-4233     cljeiv9uo104381uwwcja9z7a2      false                  

> 1
No worker type was specified. Select the worker type to use
 #     WORKER TYPE     CPU        Memory     
 1     a5              1 vCPU     2Gi        
 2     a10             2 vCPU     4Gi        
 3     a20             4 vCPU     8Gi        
 4     a40             8 vCPU     16Gi       

> 1

 #     WORKER QUEUE     ISDEFAULT     ID                              
 1     default          true          cljebq2bg2921431uwqocmfib46     

> 1
Error: KubernetesExecutor does not support minimum worker count in the request. It can only be used with CeleryExecutor
```

**What CLI Version did you experience this bug?**
Latest code commit

**This CLI bug is related to which Astronomer Platform?**
- [ ] Astro

**What Operating System is the above CLI installed on?**
Apple M1 Pro

**Comment by kushalmalani** [comment]
@shri-astro This should be fixed and merged to main. Fix will be released in version 1.18 next week

**Comment by shri-astro** [comment]
The error is still seen in the latest version of astro build pulled from main

**Comment by shri-astro** [comment]
Retest results:
```
shrividyahegde@Shrividyas-MacBook-Pro test_dep % ./astro deployment worker-queue update --concurrency 88
Select a Deployment
 #     DEPLOYMENT NAME                                                                             RELEASE NAME                 DEPLOYMENT ID                  DAG DEPLOY ENABLED     
 1     test_c                                                                                      planetic-magnify-3214        clk80wgua764381u00hyewrjb8     true                   
 2     autoqa_runtime_cpu10_mem20_8.4.0_large_a5_gcp_CeleryExecutor_without HA_14:04:35.604590     zodiacal-ionosphere-6231     clk8d8zkn223551us2ha4z7iic     false                  
 3     k                                                                                           blazing-ionosphere-0669      clk8htl1h129251czbvucbgi0s     false                  

> 3
No worker type was specified. Select the worker type to use
 #     WORKER TYPE     CPU        Memory     
 1     a5              1 vCPU     2Gi        
 2     a10             2 vCPU     4Gi        
 3     a20             4 vCPU     8Gi        
 4     a40             8 vCPU     16Gi       

> 4

 #     WORKER QUEUE     ISDEFAULT     ID                             
 1     default          true          clk8htl1i129271czbjp8b6fzu     

> 1
Error: KubernetesExecutor does not support worker concurrency in the request. It can only be used with CeleryExecutor
shrividyahegde@Shrividyas-MacBook-Pro test_dep % 
```
