### ISSUE TITLE
Failed to authenticate to the registry

### ISSUE THREAD

**Issue by p-udayakumar** [astronomer/astro-cli#156]
I’m not able to deploy my job since it fails to authenticate to registry when I login to astronomer cloud. Please find the error message below.

" sudo astro auth login astronomer.cloud
[sudo] password for pavithra:
CLUSTER WORKSPACE
astronomer.cloud 7bee299b-9745-4714-a197-0a0fd56e72eb

Switched cluster
Username (leave blank for oAuth): myemail@gmail.com
Password:
unknown flag: --password-stdin
See ‘docker login --help’.
Failed to authenticate to the registry, this can occur when registry is offline. Until authenticated you will not be able to push new images to your Airflow clusters"

I have tried with and without sudo and the error is same.

**Comment by alangsner** [comment]
I'm working with p-udayakumar on this.
We tried logging out of docker and using oAuth. Still getting the same error message.

**Comment by benjamingregory** [comment]
@p-udayakumar @alangsner 

Can you paste the error you're seeing when you authenticate via OAUTH?

**Comment by p-udayakumar** [comment]
PFA screen shot of that error

**Comment by benjamingregory** [comment]
![49306668-e80e5c00-f4a0-11e8-94ce-e14b4aa19a69](https://user-images.githubusercontent.com/8160412/49307789-7c71c200-f493-11e8-909b-3e18797afc21.png)

**Comment by benjamingregory** [comment]
@p-udayakumar Can you try upgrading to v0.7.1 and trying again?

**Comment by alangsner** [comment]
I don't know if it makes a difference but here is something to consider.

Originally we were getting a docker permission denied error since docker required root credentials. We fixed that using these steps. I wonder if this messed something up with the creds?

https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by p-udayakumar** [comment]
I upgraded to Astro CLI Version: 0.7.1 , still no luck. I get the same error

**Comment by benjamingregory** [comment]
Hmmm - I just authenticated with our cloud so this confirmed that this is a local issue.

@p-udayakumar Do you have time for a screen share next week to go through whats happening?

cc: @vparekh94

**Comment by p-udayakumar** [comment]
Sure, I'm pretty much available on Monday, if that works for you

**Comment by vparekh94** [comment]
@p-udayakumar can you try updating docker and let me know if it works after that?

**Comment by ryw** [comment]
@p-udayakumar @alangsner did you resolve this off github?

**Comment by alangsner** [comment]
Pavithra is on vacation. I'll check with her when she gets back.

**Comment by p-udayakumar** [comment]
I updated the docker and its now 'Successfully authenticated to registry.astronomer.cloud'. Thanks for all your help!
