### ISSUE TITLE
DAG folder not on python path in airflow 3.1

### ISSUE THREAD

**Issue by johnhoran** [astronomer/astro-cli#1985]
**Describe the bug**

 A common pattern we use is packaging extra python files up with the dags for use in multiple dags within a single project.  In airflow 2 this worked, but with the introduction of dag bundles in airflow 3.1 it has become broken.  I've been looking a bit at the code and specifically https://github.com/apache/airflow/pull/50385 where the dags folder has been removed from the path and replaced with the bundle root.  So in my deployment `/tmp/airflow/dag_bundles/astro/main/dags/2025-11-07T15:28:12.8895389Z/` ends up on the path.  However in astronomer this bundle root isn't the same as the dags folder, it contains the dags folder `/tmp/airflow/dag_bundles/astro/main/dags/2025-11-07T15:28:12.8895389Z/dags`.  To me this feels like a bug, when astronomer packaged up the dag folder for deployment, it should have done so such the dags end up at the root of the bundle folder, rather than in the dags subdirectory. 

For reference I'm running astronomer 3.1-3, using dag only deploys and 1.38.1 of the astro-cli

```
Please paste terminal or playground output in a code block here
```

**What CLI Version did you experience this bug?**
1.38.1

**This CLI bug is related to which Astronomer Platform?**

- [x] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

**📸 Screenshots**

**Comment by infused-kim** [comment]
We are experiencing the same thing and hope that astro can fix this soon. In the meantime I have included a workaround for this below

## Additional information

### The cloud environment is using:
- **dag_bundle_config_list:** 
  ```python
  [
      {
          'name': 'main',
          'classpath': 'astro_bundle_backend.AstroBundleBackend',
          'kwargs': {
              'refresh_interval': 5,
              'config_path': '/astro-bundle-backend-config/main',
          },
      }
  ]
  ```
- **sys path during DAG parsing:** 
  ```python
  [
      '/usr/local/bin',
      '/opt/astro/plugins/astro_bundle_backend.zip',
      '/usr/local/airflow',
      '/usr/local/lib/python312.zip',
      '/usr/local/lib/python3.12',
      '/usr/local/lib/python3.12/lib-dynload',
      '/usr/local/lib/python3.12/site-packages',
      '/usr/local/airflow/config',
      '/usr/local/airflow/plugins',
      '/tmp/airflow/dag_bundles/astro/main/dags/2025-12-23T22:43:40.8668160Z',
  ]
  ```
- **/tmp/airflow/dag_bundles/astro/main/dags/2025-12-23T22:43:40.8668160Z contents:** The `dags` directory and not the contents of the repo's `dags` dir.

### But the dev environment (`astro dev start`) is using:

- **dag_bundle_config_list:**
  ```python
  [
      {
          'name': 'dags-folder',
          'classpath': 'airflow.dag_processing.bundles.local.LocalDagBundle',
          'kwargs': {},
      }
  ]
  ```
- **sys path during DAG parsing:** 
  ```python
  [
      '/usr/local/bin',
      '/usr/local/airflow',
      '/usr/local/lib/python312.zip',
      '/usr/local/lib/python3.12',
      '/usr/local/lib/python3.12/lib-dynload',
      '/usr/local/lib/python3.12/site-packages',
      '/usr/local/airflow/config',
      '/usr/local/airflow/plugins',
      '/usr/local/airflow/dags',
  ]
  ```
- **/usr/local/airflow/dags contents:** All the files in your `dags` directory

On top of that the dev environment doesn't contain `/opt/astro/plugins/` or `/tmp/airflow/dag_bundles/`. And I couldn't find a `astro_bundle_backend` module or  `AstroBundleBackend` class.

So, it's impossible to re-create the exact environment in `dev`.

## Workaround

In the meantime, you can manually add the right path in your DAGs using this...

Add to `include/utils/astro_bundle_fix.py`:
```python
"""
Workaround for astronomer cloud's AstroBundleBackend setting the python sys
path differently than the local dev env's LocalDagBundle.
"""

import os
import sys


def fix_astro_bundle_backend_sys_path() -> None:
    """
    Add the dags folder of the AstroBundleBackend to python sys path to ensure
    modules in the dags/ directory can be imported on both the dev env and
    astronomer cloud.
    """
    for path in sys.path:
        if path.startswith('/tmp/airflow/dag_bundles/astro/main/dags/'):  # noqa: S108
            sys.path.append(os.path.join(path, 'dags'))  # noqa: PTH118
            break
```

And then in your DAGs:
```python
# ruff: noqa: E402 - Module level import not at top of file
from include.utils.astro_bundle_fix import fix_astro_bundle_backend_sys_path

fix_astro_bundle_backend_sys_path()

# [... the rest of your DAG]

from airflow.sdk import dag
from my_custom_module import foo_task
```

**Comment by tayloramurphy** [comment]
@infused-kim @johnhoran We've merged the fix for this. We'll aim to cut a release by the end of February.

**Comment by infused-kim** [comment]
Thank you  for implementing this change @tayloramurphy. However, imho this change doesn't resolve this issue and it should be re-opened.

This issue has 2 core problems:

### 1. Astro bundles `sys.path` behavior differs from regular Airflow bundles and DAG dir
In regular Airflow bundles, the `dags` dir is added to `sys.path` and you can import packages from there. In the astronomer run-time that is not the case.

Astro bundles should behave like airflow bundles. Otherwise you can't port DAGs from a regular airflow env into astro without having to make adjustments like the one in the workaround I posted.

### 2. Astro cli dev env behaves differently than astro cloud

You have attempted to address this by changing the behavior of the cli. But I would like to propose that this is the wrong place to address it. The cli shouldn't be aligned to match the non-standard behavior of the astro cloud runtime.

Instead, the cloud should be adjusted.

I would also argue that adding a non-default argument won't help improve the confusion your customers are going to experience. 

People who don't know about this problem, likely won't use this non-default cli option when developing locally. When they push to astro cloud, the astro DAGs will still fail with confusing errors... and HOPEFULLY they will then after a lot of googling stumble upon on this issue. At that point they will need to implement my workaround to ensure their DAGs are compatible between standard airflow behavior and astro cloud runtime's behavior.

And then, there won't be any reason to use this cli option.

### I understand how this came to be...

All of that being said, I understand why you solved it the way you did. This issue was opened on the `astro-cli` and not on the `astro-runtime` repo.

But that's only because the Astro runtime doesn't seem to be open source and there is no way to open an issue directly with this team.

### What now...

I think rather than releasing this fix, could you please escalate this issue to the Astro runtime team and get it fixed there?

Thanks, Kim
